services:
  - type: web
    name: Flask-YOLO-App
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 app:app"
    envVars:
      - key: SECRET_KEY
        value: "12345"
